#!/usr/bin/python


def addDashes(fn): # notice it takes a function as an argument
    def newFunction(self): # define a new function
        print "---"
        fn(self) # call the original function
        print "---"
    return newFunction


class foo:
    @addDashes       ###decorating func  to put --
    def bar(self):
        print "hi"

    @addDashes      ###decorating func  to put --
    def foobar(self):
        print "po again"


emp1 = foo()
emp1.foobar()
emp1.bar()
